### ISSUE TITLE
[iOS] Retour via slide

### ISSUE THREAD

**Issue by yaninho** [psegalen/stdrenegade#9]
Hello,

Un soucis quand, depuis l'accueil, tu cliques sur une émission, on arrive bien sur la fiche, mais si tu fais un retour via une gesture (le slide de la gauche vers la droite pour ce cas présent), on revient sur la liste des émissions et non à l'accueil.

Je sais que tu avais géré ça dans un épisode pour le bouton retour, qui lui fonctionne bien. Mais pas avec le slide du coup.

A+

**Comment by mascap17** [comment]
Je débute en React-native donc je dis sûrement une bêtise ^^

Si tu « copies » la stack navigation des programs pour la Home, tu ne devrais plus être embêté non ?
(Actuellement dans Agenda, tu pointes vers la Stack des programs et non vers une stack dédiée à la home)

**Comment by mascap17** [comment]
Voici les infos trouvées ici : https://reactnavigation.org/docs/en/tab-based-navigation.html
En espérant que cela puisse t'aider

A stack navigator for each tab

Usually tabs don't just display one screen — for example, on your Twitter feed, you can tap on a tweet and it brings you to a new screen within that tab with all of the replies. You can think of this as there being separate navigation stacks within each tab, and that's exactly how we will model it in React Navigation.

import {
  createBottomTabNavigator,
  createStackNavigator,
  createAppContainer,
} from 'react-navigation';

class DetailsScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Details!</Text>
      </View>
    );
  }
}

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        {/* other code from before here */}
        <Button
          title="Go to Details"
          onPress={() => this.props.navigation.navigate('Details')}
        />
      </View>
    );
  }
}

class SettingsScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        {/* other code from before here */}
        <Button
          title="Go to Details"
          onPress={() => this.props.navigation.navigate('Details')}
        />
      </View>
    );
  }
}

const HomeStack = createStackNavigator({
  Home: HomeScreen,
  Details: DetailsScreen,
});

const SettingsStack = createStackNavigator({
  Settings: SettingsScreen,
  Details: DetailsScreen,
});

export default createAppContainer(createBottomTabNavigator(
  {
    Home: HomeStack,
    Settings: SettingsStack,
  },
  {
    /* Other configuration remains unchanged */
  }
));

**Comment by psegalen** [comment]
@mascap17 j'ai commit le code de ce midi (commit lié à cette issue) si tu veux essayer de faire une PR

**Comment by mascap17** [comment]
j'ai pas réussi à récupérer le code fonctionnel "assez rapidement" (l'absence des Node_module je suppose), néanmoins voici un Example de ma proposition :


import React from "react"
import { createStackNavigator } from "react-navigation"

import Home from "./Home"
import ProgramsDetails from "../programs/ProgramsDetails"

import Header from "../../components/Header"

export const HomeRoutes = {
    homeHome: "HOME_HOME",
    homeDetails: "HOME_DETAILS",
}

const stackNavigator = createStackNavigator(
    {
        [HomeRoutes.homeHome]: Home,
        [HomeRoutes.homeDetails]: ProgramsDetails,
    },
    {
        navigationOptions: ({ navigation }) => {
            const { params = {} } = navigation.state
            const { scrollContentYOffset } = params
            return {
                header: ({ index }) => (
                    <Header
                        navigation={navigation}
                        scrollContentYOffset={scrollContentYOffset}
                        shouldShowBackButton={index !== 0}
                        params={params}
                    />
                ),
            }
        },
    }
)

const AppContainer = createAppContainer(stackNavigator);
export default class HomeContainer extends Component {//attention faut faire l'import
popToRoot() {
  if (this.navigator != undefined && this.navigator.state.nav.index > 0) {
    let k =this. navigator.state.nav.routes[1].key;
    this.navigator.dispatch(NavigationActions.back({ key: k }));
  }
}
render(){
return (
      <View
        style={{
          flex: 1,
        }}
      >
        <NavigationEvents onWillBlur={() => this.popToRoot()} />
<AppContainer ref={navigator => (this.navigator = navigator)} />
</View>
}
}

**Comment by psegalen** [comment]
@mascap17 maintenant que tu donné ton sub prime à la chaîne, tu peux demander une invitation au Slack de la chaîne si tu veux qu'on discute plus facilement ! :)
Alternativement, je suis aussi sur notre Discord public : https://discord.gg/PCNgbxY

**Comment by mascap17** [comment]
@psegalen effectivement ça sera plus simple, je suis déjà sur le Discord (Pascal M avec mon chat en photo de profil)

Je suis pas trop fan de Slack (PS : je donnais déjà(encore) sur Tipeee avant le sub Prime)
